### PR TITLE
deleted files from old tools for .net core (xproj and project.json)

### PR DESCRIPTION
**Pull request by SychevIgor**
deleted files from old tools for .net core (xproj and project.json)

### CODE REVIEW

**Comment by SychevIgor** [comment]
Hello colleagues! @schaabs @bryanar @brianrob any opinion about this PR?

**Comment by ghost** [comment]
Heya, I am not at Microsoft anymore, so I shouldn't comment at all. Schaabs is at Azure now. @brianrob (HI) is the only guy who can authoritatively respond I think.

**Comment by SychevIgor** [comment]
@brianrob could you look on this PR?

**Comment by brianrob** [comment]
@DrewScoggins now owns this area and should be able to help.

**Comment by SychevIgor** [comment]
@DrewScoggins could you please look on this PR?

**Comment by ghost** [comment]
Also what happened to all the code here? It looks like someone gutted this. Oh wait, Schaabs did. I wonder why he did that...lol.

**Comment by schaabs** [comment]
@bryanar I moved the dumpling code out into it's own repo, https://github.com/microsoft/dumpling, and removed the code from here to avoid confusion.

**Comment by ghost** [comment]
Why does this repository still exist?
Why not add it to the commit message?
Why is the dumpling website still up but now defunct?
What happened to the readme? 

Lots more questions than answers still. The intentions of this group are muddy. Maybe a proper cleanup is in order?

**Comment by SychevIgor** [comment]
nobody care

**Pull request closed without merging**
