### PR TITLE
Added tool to list build id of modules in a core dump

### PR DESCRIPTION
**Pull request by leculver**
Added a tool to list modules within a core dump and their associated build id.

### CODE REVIEW

**Comment by leculver** [comment]
@schaabs is added to the review. #Closed

**Comment by leculver** [comment]
@brianrob is added to the review. #Closed

**Comment by leculver** [comment]
@schaabs: I updated the tool to work with libraries and executables as well.  It turns out the build id is still kept in the program header and not the section header, as I thought.

**Comment by brianrob** [comment]
Overall, LGTM.  One question - do we really want to run this on Windows?  I would expect that we'd want to do this and other core dump related work on Linux, and so we should probably not want to build this tool with VS.

**Comment by schaabs** [comment]
:shipit:

**Comment by schaabs** [comment]
Also LGTM, but I agree with @brianrob above.  We should port this to build with CMAKE or something like that, as we'll most likely be using this on the OS where we're analyzing core dumps ect.  That being said I think we can merge this in now, and look at refactoring the build later.

**Comment by schaabs** [comment]
and apparently hamster in a fedora means 'approved'

**Comment by leculver** [comment]
@brianrob @schaabs: The Visual Studio stuff here is because I actually used Visual Studio's tools for linux to build this project:  https://blogs.msdn.microsoft.com/vcblog/2016/03/30/visual-c-for-linux-development/

You set up a target Linux machine by giving VS your SSH credentials, and you can code/debug via Visual Studio (it compiles and debugs with G++/GDB respectively).

Feel free to strip out the Visual Studio projects, but I found them useful...

**Comment by schaabs** [comment]
Nice, please leave the VS projects in the check-in.

**Comment by leculver** [comment]
Will do.  We can just add CMAKE files later so it compiles for both.

**Comment by brianrob** [comment]
Oh, cool.  :shipit:

**Pull request merged**
